routes/admin.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Здесь описаны административные маршруты
| Для доступа требуется авторизация пользователя
|
*/

Route::resource('users', UserController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Validator;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function($user) {
            Validator::make($user->toArray(), [
                'email' => 'required|email|max:255|unique:users',
                'password' => 'required|min:6|confirmed',
            ])->validate();
        });

        static::saving(function($user) {
            Validator::make($user->toArray(), [
                'first_name' => 'max:255',
                'last_name' => 'max:255'
            ])->validate();
        });
    }


}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class AuthController extends Controller
{
    public function index()
    {
        return view('auth.login');
    }

    public function login(Request $request)
    {
        $credentials = [
            'email' => $request->input('email'),
            'password' => $request->input('password')
        ];

        $user = Sentinel::forceAuthenticate($credentials, $request->has('remember'));

        if (!$user) {
            return back()->withErrors(['login' => 'Неверно введен логин или пароль']);
        }

        return redirect('/');

    }

    public function logout()
    {
        Sentinel::logout();

        return redirect('/');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/RegisterController.php
<?php

namespace App\Http\Controllers;

use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;

class RegisterController extends Controller
{
    public function index()
    {
        return view('auth.registration');
    }

    public function register(Request $request)
    {
        $credentials = [
            'email' => $request->input('email'),
            'password' => $request->input('password'),
            'first_name' => $request->input('first_name'),
            'last_name' => $request->input('last_name')
        ];

        Sentinel::registerAndActivate($credentials);

        return redirect()->route('users.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Show users list.
     */
    public function index(Request $request)
    {
        $users = User::orderBy('id', 'desc')->paginate(25);

        return view('admin.users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new user.
     */
    public function create(Request $request)
    {
        return view('admin.users.form');
    }

    /**
     * Store a newly created user in storage.
     */
    public function store(Request $request)
    {
        ddd('store');
    }

    /**
     * Display the specified user.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('admin.users.form', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified user.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        ddd('edit');
    }

    /**
     * Update the specified user in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->update($request->all());

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified user from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/layout.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Skeleton</title>

    <link rel="stylesheet" href="{{ mix('css/style.css') }}">

    @yield('style')
</head>
<body>

    <div class="container-fluid">
        <header class="row mb-5 mt-3">

            <div class="col-12">
                <a href="">{{ $user->email }}</a>

                <a href="{{ route('login.doLogout') }}" class="btn btn-danger">Выход</a>
            </div>
        </header>

        <main>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @yield('content')
        </main>

        <footer></footer>
    </div>


@yield('script')

</body>
</html>

resources/views/admin/users/form.blade.php
@extends('admin.layout')

@section('content')
    <form action="{{ route('users.update', ['user' => $user->id]) }}" method="post">
        @if($user)
            @method('put')
        @endif

        @csrf

        <div class="form-group">
            <label for="">Имя</label>
            <input type="text" class="form-control" name="first_name" value="{{ $user->first_name }}">
        </div>

        <div class="form-group">
            <label for="">Фамилия</label>
            <input type="text" class="form-control" name="last_name" value="{{ $user->last_name }}">
        </div>

        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout')

@section('content')
    <table class="table">
        <thead>
        <tr>
            <th>role</th>
            <th>email</th>
            <th>first name</th>
            <th>last name</th>
            <th>last login</th>
            <th>registered at</th>
        </tr>
        </thead>

        <tbody>
        @foreach($users as $user)
        <tr>
            <td></td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->first_name }}</td>
            <td>{{ $user->last_name }}</td>
            <td>{{ $user->last_login }}</td>
            <td>{{ $user->created_at }}</td>
        </tr>
        @endforeach
        </tbody>
    </table>
@endsection